name: Lab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright as dependency
      run: npm install @playwright/test --save-dev

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Fix execution permissions
      run: chmod +x node_modules/.bin/playwright

    - name: Run tests
      run: npx playwright test
