name: Lab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright
      run: npm install @playwright/test --save-dev

    - name: Debug Playwright path
      run: |
        echo "Playwright path:"
        which playwright || echo "Playwright not found"
        ls -l node_modules/.bin/

    - name: Fix Playwright permissions
      run: chmod +x node_modules/.bin/playwright || echo "No permission issue"

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: npx playwright test
