name: Lab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Додаємо команду білду перед запуском сервера

      - name: Install Playwright
        run: npm install @playwright/test --save-dev

      - name: Install http-server
        run: npm install -g http-server

      - name: Fix http-server permissions
        run: chmod +x node_modules/.bin/http-server || echo "No permission issue"

      - name: Start local server
        run: npx http-server ./dist -p 3000 &

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test
